services:
  postgres:
    image: postgres:15
    container_name: up_postgres
    restart: always
    env_file: ./api/.env
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./api
    container_name: users-posts
    restart: always
    depends_on:
      - postgres
    env_file: ./api/.env
    ports:
      - "4000:4000"

volumes:
  postgres_data:
